#!/bin/sh

[ -r /etc/default/syntrolcam ] && . /etc/default/syntrolcam


case "$START_CAMERA" in
        [Nn]*)
                exit 0
                ;;
esac

if [ ! -f /usr/bin/SyntroLCam ]; then
    exit 0
fi

start_camera() 
{
    if [ ! -d /home/root/syntro ]; then
        mkdir /home/root/syntro
    fi

    cd /home/root/syntro

    /usr/bin/SyntroLCam -s/etc/syntro/SyntroLCam.ini -c -d    
}

case "$1" in
    start)
        echo "Starting SyntroLCam"
        start_camera
        ;;

    stop)
        echo "Stopping SyntroLCam"
        killall SyntroLCam
        ;;

    restart)
        echo "Stopping SyntroLCam"
        killall SyntroLCam
        sleep 3
        echo "Starting SyntroLCam"
        start_camera
        ;;

    *)
        echo "Usage: /etc/init.d/syntrolcam {start|stop|restart}"
        exit 2
esac

