#!/bin/sh

[ -x /usr/bin/mender ] || exit 0

start_mender()
{
    if [ ! -d /data/mender ]; then
        mkdir -p -m 0700 /data/mender
    fi

    if [ ! -f /data/mender/device_type ]; then
        echo "device_type=beaglebone" > /data/mender/device_type
    fi

    ln -sf /etc/mender/tenant.conf /var/lib/mender/authtentoken

    mender -daemon &
}

stop_mender()
{
    killall mender
}

case "$1" in
    start)
        echo "Starting mender daemon"
        start_mender
        ;;

    stop)
        echo "Stopping mender daemon"
        stop_mender
        ;;
esac
