#!/bin/sh

BT_ATTACH_ARGS="/dev/ttyO3 texas 3000000"

[ -r /etc/default/bt-init ] && . /etc/default/bt-init

if [ ! -x /usr/bin/hciattach ]; then
    exit 0
fi

attach_bt() {
    case "$START_BT" in
        [Nn]*)
            exit 0
            ;;
    esac

    echo "Attaching bluetooth"

    if [ ! -d /sys/class/gpio/gpio60 ]; then
        echo 60 > /sys/class/gpio/export
        echo high > /sys/class/gpio/gpio60/direction
    else
        echo 1 > /sys/class/gpio/gpio60/value
    fi

    /usr/bin/hciattach ${BT_ATTACH_ARGS}
}

disable_bt() {
    echo "Disabling bluetooth"

    if [ -d /sys/class/gpio/gpio60 ]; then
        echo 0 > /sys/class/gpio/gpio60/value
    fi
}

case "$1" in
    start)
        attach_bt
        ;;

    stop)
        disable_bt
        ;;

    restart)
        disable_bt
        sleep 3
        attach_bt 
        ;;

    *)
        echo "Usage: /etc/init.d/bt-init {start|stop|restart}"
        exit 2
esac

