#!/bin/sh

[ -r /etc/default/boot-flags ] && . /etc/default/boot-flags

case "${CHECK_BOOT_FLAGS_PARTITION}" in
    [Nn]*)
        exit 0
        ;;
esac

[ -x /usr/bin/syskeep ] || exit 0

/usr/bin/syskeep -quiet
